CREATE TABLE IF NOT EXISTS stat.latency_stats_1day
(
    tx_date date,
    no_ord integer DEFAULT 0,
    med_latency integer DEFAULT 0,
    avg_latency integer DEFAULT 0,
    min_latency integer DEFAULT 0,
    max_latency integer DEFAULT 0,
    no_ord_me_vrd_in_type_1 integer DEFAULT 0,
    no_ord_me_vrd_in_type_2 integer DEFAULT 0,
    no_ord_me_vrd_in_type_3 integer DEFAULT 0,
    no_ord_me_vrd_in_type_4 integer DEFAULT 0,
    no_ord_me_vrd_in_type_5 integer DEFAULT 0,
    no_ord_me_vrd_in_type_6 integer DEFAULT 0,
    no_ord_me_net_in_type_1 integer DEFAULT 0,
    no_ord_me_net_in_type_2 integer DEFAULT 0,
    no_ord_me_net_in_type_3 integer DEFAULT 0,
    no_ord_me_net_in_type_4 integer DEFAULT 0,
    no_ord_me_net_in_type_5 integer DEFAULT 0,
    no_ord_me_net_in_type_6 integer DEFAULT 0,
    no_ord_gw_net_in_type_1 integer DEFAULT 0,
    no_ord_gw_net_in_type_2 integer DEFAULT 0,
    no_ord_gw_net_in_type_3 integer DEFAULT 0,
    no_ord_gw_net_in_type_4 integer DEFAULT 0,
    no_ord_gw_net_in_type_5 integer DEFAULT 0,
    no_ord_gw_net_in_type_6 integer DEFAULT 0,
    protocol character varying(10) COLLATE pg_catalog."default",
    partition smallint,
    market character varying(1) COLLATE pg_catalog."default",
    location character varying(10) COLLATE pg_catalog."default",
    under_sla integer
)
