-- Table: stat.lr_users

-- DROP TABLE IF EXISTS stat.lr_users;

CREATE TABLE IF NOT EXISTS stat.lr_users
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    username character varying(255) COLLATE pg_catalog."default" NOT NULL,
    employee_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    full_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    organization character varying(255) COLLATE pg_catalog."default",
    email character varying(63) COLLATE pg_catalog."default",
    last_logged_in timestamp(6) with time zone,
    CONSTRAINT pk_lr_users PRIMARY KEY (id)
        USING INDEX TABLESPACE statdb_test,
    CONSTRAINT uk_lr_users_employee_id UNIQUE (employee_id)
        USING INDEX TABLESPACE statdb_test,
    CONSTRAINT ck_lr_users_employee_id_not_blank CHECK (btrim(employee_id::text) <> ''::text),
    CONSTRAINT ck_lr_users_full_name_not_blank CHECK (btrim(full_name::text) <> ''::text),
    CONSTRAINT ck_lr_users_username_not_blank CHECK (btrim(username::text) <> ''::text)
)

-- Table: stat.lr_roles

-- DROP TABLE IF EXISTS stat.lr_roles;

CREATE TABLE IF NOT EXISTS stat.lr_roles
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY
        ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    code character varying(100) COLLATE pg_catalog."default" NOT NULL,
    display_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description character varying(500) COLLATE pg_catalog."default",
    active boolean NOT NULL DEFAULT true,
    sync_assignable boolean NOT NULL DEFAULT false,
    manual_assignable boolean NOT NULL DEFAULT false,
    CONSTRAINT pk_lr_roles PRIMARY KEY (id)
        USING INDEX TABLESPACE statdb_test,
    CONSTRAINT uk_lr_roles_code UNIQUE (code)
        USING INDEX TABLESPACE statdb_test,
    CONSTRAINT ck_lr_roles_code_not_blank CHECK (btrim(code::text) <> ''::text),
    CONSTRAINT ck_lr_roles_display_name_not_blank CHECK (btrim(display_name::text) <> ''::text)
)

CREATE TABLE IF NOT EXISTS stat.lr_user_roles
(
    user_id uuid NOT NULL,
    role_id bigint NOT NULL,
    sync_assigned boolean NOT NULL DEFAULT false,
    manual_assigned boolean NOT NULL DEFAULT false,
    manual_assigned_at timestamp(6) with time zone,
    manual_assigned_by character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT pk_lr_user_roles PRIMARY KEY (user_id, role_id)
        USING INDEX TABLESPACE statdb_test,
    CONSTRAINT fk_lr_user_roles_role FOREIGN KEY (role_id)
        REFERENCES stat.lr_roles (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT,
    CONSTRAINT fk_lr_user_roles_user FOREIGN KEY (user_id)
        REFERENCES stat.lr_users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT ck_lr_user_roles_has_assignment_source CHECK (
        sync_assigned = true OR manual_assigned = true
    ),
    CONSTRAINT ck_lr_user_roles_manual_metadata CHECK (
        manual_assigned = true
        AND manual_assigned_by IS NOT NULL
        AND manual_assigned_at IS NOT NULL
        AND btrim(manual_assigned_by::text) <> ''::text
        OR manual_assigned = false
        AND manual_assigned_at IS NULL
        AND manual_assigned_by IS NULL
    )
)