-- ============================================================================
-- V1__role_rehaul.sql — full rebuild of the auth/role schema.
--
-- Per decision (REHAUL-PLAN.md §3): the old tables hold nothing worth keeping,
-- so everything is dropped and recreated. Users repopulate themselves at next
-- login. Run this BEFORE deploying the new build — the application refuses to
-- boot without the seeded ADMIN / STANDARD_USER rows.
--
-- Tablespace clauses (USING INDEX TABLESPACE statdb_test) were dropped for
-- portability; re-add them if your environment requires them.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- stat.user_page_history (page-visit analytics) references lr_users but is
-- NOT part of this rebuild. Its data is expendable (per decision), so: empty
-- it, remember its FK definition(s) from the catalog, detach them so lr_users
-- can be dropped, and re-attach them verbatim at the end of this script.
-- No-ops when the table does not exist (e.g. a fresh environment).
-- ----------------------------------------------------------------------------
DROP TABLE IF EXISTS _uph_fk;
CREATE TEMP TABLE _uph_fk AS
SELECT conname, pg_get_constraintdef(oid) AS definition
  FROM pg_constraint
 WHERE conrelid = to_regclass('stat.user_page_history')
   AND confrelid = to_regclass('stat.lr_users')
   AND contype = 'f';

DO $$
DECLARE
    fk record;
BEGIN
    IF to_regclass('stat.user_page_history') IS NULL THEN
        RETURN;
    END IF;

    EXECUTE 'TRUNCATE stat.user_page_history';

    FOR fk IN SELECT conname FROM _uph_fk LOOP
        EXECUTE format('ALTER TABLE stat.user_page_history DROP CONSTRAINT %I', fk.conname);
    END LOOP;
END $$;

-- ---------------------------------------------------------------- drop (children first)
DROP TABLE IF EXISTS stat.lr_refresh_tokens;
DROP TABLE IF EXISTS stat.lr_role_audit;
DROP TABLE IF EXISTS stat.lr_role_cn_rules;
DROP TABLE IF EXISTS stat.lr_role_pages;
DROP TABLE IF EXISTS stat.lr_user_roles;
DROP TABLE IF EXISTS stat.user_member_of;
DROP TABLE IF EXISTS stat.lr_users;
DROP TABLE IF EXISTS stat.lr_roles;

-- ---------------------------------------------------------------- lr_users
CREATE TABLE stat.lr_users
(
    id             uuid                     NOT NULL DEFAULT gen_random_uuid(),
    username       varchar(255)             NOT NULL,
    employee_id    varchar(255)             NOT NULL,
    full_name      varchar(255)             NOT NULL,
    organization   varchar(255),
    email          varchar(63),
    last_logged_in timestamptz,
    CONSTRAINT pk_lr_users PRIMARY KEY (id),
    CONSTRAINT uk_lr_users_employee_id UNIQUE (employee_id),
    CONSTRAINT uk_lr_users_username UNIQUE (username),
    CONSTRAINT ck_lr_users_username_not_blank CHECK (btrim(username) <> ''),
    CONSTRAINT ck_lr_users_employee_id_not_blank CHECK (btrim(employee_id) <> ''),
    CONSTRAINT ck_lr_users_full_name_not_blank CHECK (btrim(full_name) <> '')
);

-- LDAP groups seen at the user's last login. Read by refresh-time rule
-- re-evaluation and shown in the admin UI ("why does this user have role X").
CREATE TABLE stat.user_member_of
(
    user_id   uuid         NOT NULL,
    member_of varchar(512) NOT NULL,
    CONSTRAINT pk_user_member_of PRIMARY KEY (user_id, member_of),
    CONSTRAINT fk_user_member_of_user FOREIGN KEY (user_id)
        REFERENCES stat.lr_users (id) ON DELETE CASCADE
);

-- ---------------------------------------------------------------- lr_roles
CREATE TABLE stat.lr_roles
(
    id                bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    code              varchar(100) NOT NULL,
    display_name      varchar(255) NOT NULL,
    description       varchar(500),
    active            boolean      NOT NULL DEFAULT true,
    sync_assignable   boolean      NOT NULL DEFAULT false,
    manual_assignable boolean      NOT NULL DEFAULT false,
    CONSTRAINT pk_lr_roles PRIMARY KEY (id),
    CONSTRAINT uk_lr_roles_code UNIQUE (code),
    CONSTRAINT ck_lr_roles_code_not_blank CHECK (btrim(code) <> ''),
    CONSTRAINT ck_lr_roles_display_name_not_blank CHECK (btrim(display_name) <> '')
);

-- ---------------------------------------------------------------- lr_user_roles
-- One row per (user, role, source). SYNC rows belong to the login/refresh
-- synchronizer; MANUAL rows belong to admins. The two never share a row, so a
-- manual grant survives leaving the LDAP group and vice versa — by structure.
CREATE TABLE stat.lr_user_roles
(
    id         bigint      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id    uuid        NOT NULL,
    role_id    bigint      NOT NULL,
    source     varchar(10) NOT NULL,
    granted_at timestamptz NOT NULL DEFAULT now(),
    granted_by varchar(255),
    CONSTRAINT pk_lr_user_roles PRIMARY KEY (id),
    CONSTRAINT uk_lr_user_roles UNIQUE (user_id, role_id, source),
    CONSTRAINT fk_lr_user_roles_user FOREIGN KEY (user_id)
        REFERENCES stat.lr_users (id) ON DELETE CASCADE,
    -- RESTRICT is the database half of "a role cannot be deleted while held".
    CONSTRAINT fk_lr_user_roles_role FOREIGN KEY (role_id)
        REFERENCES stat.lr_roles (id) ON DELETE RESTRICT,
    CONSTRAINT ck_lr_user_roles_source CHECK (source IN ('SYNC', 'MANUAL')),
    CONSTRAINT ck_lr_user_roles_granted_by CHECK (
        (source = 'MANUAL' AND granted_by IS NOT NULL AND btrim(granted_by) <> '')
        OR (source = 'SYNC' AND granted_by IS NULL)
    )
);

CREATE INDEX ix_lr_user_roles_role ON stat.lr_user_roles (role_id);

-- ---------------------------------------------------------------- lr_role_cn_rules
-- "If one of the user's LDAP groups has this CN, grant this role."
-- cn_value is what the admin typed (display only). cn_key is the output of the
-- Java LdapNameNormalizer and is THE ONLY FIELD EVER COMPARED. Never compare
-- with SQL lower() — Postgres and the Java normalizer disagree on Turkish I.
CREATE TABLE stat.lr_role_cn_rules
(
    id          bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    role_id     bigint       NOT NULL,
    cn_value    varchar(512) NOT NULL,
    cn_key      varchar(512) NOT NULL,
    match_mode  varchar(10)  NOT NULL DEFAULT 'EXACT',
    active      boolean      NOT NULL DEFAULT true,
    description varchar(500),
    updated_by  varchar(255) NOT NULL,
    updated_at  timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT pk_lr_role_cn_rules PRIMARY KEY (id),
    CONSTRAINT uk_lr_role_cn_rules UNIQUE (role_id, cn_key, match_mode),
    CONSTRAINT fk_lr_role_cn_rules_role FOREIGN KEY (role_id)
        REFERENCES stat.lr_roles (id) ON DELETE CASCADE,
    CONSTRAINT ck_lr_role_cn_rules_mode CHECK (match_mode IN ('EXACT', 'CONTAINS')),
    CONSTRAINT ck_lr_role_cn_rules_value_not_blank CHECK (btrim(cn_value) <> ''),
    CONSTRAINT ck_lr_role_cn_rules_key_not_blank CHECK (btrim(cn_key) <> '')
);

-- ---------------------------------------------------------------- lr_role_pages
-- "Role X may see page Y." Page codes are constants in PageCodes.java; which
-- roles map to them is runtime data, editable from the admin UI.
CREATE TABLE stat.lr_role_pages
(
    role_id   bigint      NOT NULL,
    page_code varchar(50) NOT NULL,
    CONSTRAINT pk_lr_role_pages PRIMARY KEY (role_id, page_code),
    CONSTRAINT fk_lr_role_pages_role FOREIGN KEY (role_id)
        REFERENCES stat.lr_roles (id) ON DELETE CASCADE
);

-- ---------------------------------------------------------------- lr_refresh_tokens
-- One row per active session. Only the SHA-256 hash of the token is stored.
CREATE TABLE stat.lr_refresh_tokens
(
    id         uuid        NOT NULL DEFAULT gen_random_uuid(),
    user_id    uuid        NOT NULL,
    token_hash varchar(64) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz NOT NULL,
    CONSTRAINT pk_lr_refresh_tokens PRIMARY KEY (id),
    CONSTRAINT uk_lr_refresh_tokens_hash UNIQUE (token_hash),
    CONSTRAINT fk_lr_refresh_tokens_user FOREIGN KEY (user_id)
        REFERENCES stat.lr_users (id) ON DELETE CASCADE
);

CREATE INDEX ix_lr_refresh_tokens_user ON stat.lr_refresh_tokens (user_id);

-- ---------------------------------------------------------------- lr_role_audit
-- Append-only. No foreign keys on purpose: history must survive deletion of
-- the user or role it describes.
CREATE TABLE stat.lr_role_audit
(
    id          bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    happened_at timestamptz  NOT NULL DEFAULT now(),
    action      varchar(20)  NOT NULL,
    actor       varchar(255) NOT NULL,
    username    varchar(255),
    role_code   varchar(100),
    detail      varchar(500),
    CONSTRAINT pk_lr_role_audit PRIMARY KEY (id)
);

-- ============================================================================
-- Seeds
-- ============================================================================

INSERT INTO stat.lr_roles (code, display_name, description, active, sync_assignable, manual_assignable)
VALUES ('STANDARD_USER', 'Standard User', 'Baseline role granted automatically to every authenticated user', true, true, false),
       ('ADMIN', 'Administrator', 'Role management and full page access', true, false, true),
       ('TRANSACTION', 'Transaction', 'Access to the transaction search pages', true, true, true),
       ('ANALYTICS', 'Analytics', 'Access to the page visit analytics page', true, true, true);

INSERT INTO stat.lr_role_pages (role_id, page_code)
SELECT r.id, p.code
  FROM stat.lr_roles r
       CROSS JOIN unnest(ARRAY ['LATENCY_DAILY', 'LATENCY_RTT', 'LATENCY_GROUPED']) AS p(code)
 WHERE r.code = 'STANDARD_USER'
UNION ALL
SELECT r.id, 'TRANSACTIONS' FROM stat.lr_roles r WHERE r.code = 'TRANSACTION'
UNION ALL
SELECT r.id, 'ANALYTICS' FROM stat.lr_roles r WHERE r.code = 'ANALYTICS';
-- ADMIN needs no page rows: the backend gives ADMIN every page at token build.

-- The one existing CN rule. cn_key is the normalizer's output — 'ş' preserved
-- but 'kanallari' ends in a DOTTED i. That is not a typo (see REHAUL-PLAN §3.4);
-- it must match verification/NormalizerCheck.java exactly.
INSERT INTO stat.lr_role_cn_rules (role_id, cn_value, cn_key, match_mode, active, description, updated_by)
SELECT r.id,
       'İletişim Kanalları Servisi',
       'iletişim kanallari servisi',
       'EXACT',
       true,
       'Transaction pages for the communication channels service',
       'SYSTEM_SEED'
  FROM stat.lr_roles r
 WHERE r.code = 'TRANSACTION';

-- ============================================================================
-- Re-attach the user_page_history foreign key(s) captured at the top,
-- exactly as they were (same name, same columns, same ON DELETE behavior).
-- ============================================================================
DO $$
DECLARE
    fk record;
BEGIN
    FOR fk IN SELECT conname, definition FROM _uph_fk LOOP
        EXECUTE format(
            'ALTER TABLE stat.user_page_history ADD CONSTRAINT %I %s',
            fk.conname, fk.definition
        );
    END LOOP;
END $$;

DROP TABLE IF EXISTS _uph_fk;

-- ============================================================================
-- One-time ADMIN bootstrap (run manually AFTER the intended admin has logged
-- in once — their lr_users row must exist). Replace <admin-username>.
-- ============================================================================
-- INSERT INTO stat.lr_user_roles (user_id, role_id, source, granted_by)
-- SELECT u.id, r.id, 'MANUAL', 'BOOTSTRAP'
--   FROM stat.lr_users u, stat.lr_roles r
--  WHERE u.username = '<admin-username>' AND r.code = 'ADMIN'
-- ON CONFLICT DO NOTHING;
--
-- INSERT INTO stat.lr_role_audit (action, actor, username, role_code, detail)
-- VALUES ('GRANT', 'BOOTSTRAP', '<admin-username>', 'ADMIN', 'One-time bootstrap of the first administrator');
